import os
import json
import subprocess
import time

def test_metrics_file_generated():
    # Remove any existing metrics file to ensure a fresh run
    if os.path.exists("metrics.json"):
        os.remove("metrics.json")
    
    # Run the model script
    result = subprocess.run(["python", "src/model.py"], capture_output=True, text=True)
    
    # Allow a moment for the file to be written
    time.sleep(5)
    
    # Check that metrics.json has been created
    assert os.path.exists("metrics.json"), "metrics.json was not generated by model.py"
    
    # Open the metrics file and check required keys
    with open("metrics.json", "r") as f:
        metrics = json.load(f)
    
    required_keys = ["train_accuracy", "test_accuracy", "trained_weights", "trained_bias", "epochs"]
    for key in required_keys:
        assert key in metrics, f"Missing key '{key}' in metrics.json"
    
    # Optional: Verify that accuracy values are within expected range
    assert 0 <= metrics["train_accuracy"] <= 1, "Train accuracy is out of bounds"
    assert 0 <= metrics["test_accuracy"] <= 1, "Test accuracy is out of bounds"
